#DATA
data_root: /mnt/data/gxy/PIA_Data/npy/3D
dataset: ISLES22
infer_root: /mnt/data/gxy/PIA_Data/raw/3D
split_path: /mnt/data/gxy/PIA_Data/raw/3D/ISLES22_1p5/split4.json
labtype: 'part'
in_channels: 2

#TRAIN
start_epoch: 0
epochs: 400
lr: 0.002
lr_decay: poly
momentum: 0.9
weight_decay: 0.0001
warmup_epoch: 3
seed: 2025
pretrain: False

batch_size: 1
training_size: [64, 128, 128]
window_size: [64, 128, 128]
aux_weights: [0.6, 0.3, 0.1]
print_freq: 50
corr_rec_freq: 50

color_prob: 0.3
flip_prob: 0.1

val_freq: 3

#Correction
identifier: seghead
corr_start: 80
Fcorr_ratio: 0.0001
Bcorr_ratio: 0.00001
# Fcorr_ratio: 0.01
# Bcorr_ratio: 0.001
rho_start: 0.95
rho_end: 0.8
rho_start_: 0.05
rho_end_: 0.2
eval_corr: True

#PriorLearning
pcorr_start: 1200
Fprior_num: 5
Bprior_num: 5
liver_ema: 0.7

rank: 0
num_workers: 2