#DATA
data_root: /mnt/data/gxy/PIA_Data/npy/3D
dataset: MS_crop
infer_root: /mnt/data/gxy/PIA_Data/raw/3D
split_path: /mnt/data/gxy/PIA_Data/raw/3D/MS/split.json
labtype: 'part'
in_channels: 1

#TRAIN
start_epoch: 0
epochs: 400
lr: 0.002
lr_decay: poly
momentum: 0.9
weight_decay: 0.0001
warmup_epoch: 3
seed: 2025

batch_size: 1
training_size: [64, 128, 128]
window_size: [64, 128, 128]
aux_weights: [0.6, 0.3, 0.1]
print_freq: 50

corr_rec_freq: 50
correct_freq: 10
threshold: 0.9
conf_threshold: 0.8

color_prob: 0.3
flip_prob: 0.1 

val_freq: 3

#Correction
identifier: seghead
corr_start: 120
Fcorr_ratio: 0.0005
Bcorr_ratio: 0.00005
rho_start: 0.95
rho_end: 0.8
rho_start_: 0.05
rho_end_: 0.2
eval_corr: True

#PriorLearning
pcorr_start: 120
Fprior_num: 5
Bprior_num: 5
liver_ema: 0.7

rank: 0
num_workers: 2